export default {
  childrenTitle: '.cd-dashboard-children__header',
  children: '.cd-dashboard-children .cd-dashboard-children__child',
  childrenNames: '.cd-dashboard-children__name',
  childrenBadges: '.cd-dashboard-children__badge',
  childrenLink: '.cd-dashboard-children__cta',
  newsTitle: '.cd-dashboard-news__header',
  newsEntries: '.cd-dashboard-news__posts',
  newsEntryTitle: '.cd-dashboard-news__post-title',
  newsEntryDate : '.cd-dashboard-news__post-date',
  // newsEntryCategory: '.cd-dashboard-news__post-type',
  projectTitle: '.cd-dashboard-projects__header',
  projectCards: '.cd-dashboard-projects__cards',
  projectCard: '.cd-dashboard-projects__card',
};
