export default {
  sidebar: '.cd-dashboard__right-column',
  childrenTitle: '.cd-dashboard-children__header',
  children: '.cd-dashboard-children .cd-dashboard-children__child',
  childrenNames: '.cd-dashboard-children__name',
  childrenBadges: '.cd-dashboard-children__badge',
  childrenLink: '.cd-dashboard-children__cta',
  newsTitle: '.cd-dashboard-news__header',
  newsEntries: '.cd-dashboard-news__posts',
  newsEntryTitle: '.cd-dashboard-news__post-title',
  newsEntryDate: '.cd-dashboard-news__post-date',
  // newsEntryCategory: '.cd-dashboard-news__post-type',
  pendingRequests: '.cd-dashboard-pending-requests__request',
  pendingRequestsInfo: '.cd-dashboard-pending-requests__info',
  projectTitle: '.cd-dashboard-projects__header',
  projectCards: '.cd-dashboard-projects__cards',
  projectCard: '.cd-dashboard-projects__card',
  statsTitle: '.cd-dashboard-stats__header',
  statsCategory: '.cd-dashboard-stats__category',
  statsNbYouthChart: '.cd-dashboard-stats__description',
  statsYouthGenderChart: '.cd-dashboard-stats__circle',
  statsUseZenMessage: '.cd-dashboard-stats p',
  statsYouthGirlsHint: '.cd-dashboard-stats__chart-pie-hint',
};
