export default {
  header: '.cd-login__header',
  loginBox: '.cd-login__box',
  email: 'input[type=email]',
  password: 'input[type=password]',
  login: 'input[type=submit]',
  register: '.cd-login__register',
  forgotPassword: '.cd-login__forgot-password',
  emailReqError: '.cd-login__email-req-err',
  emailFormatError: '.cd-login__email-format-err',
  passwordReqError: '.cd-login__password-req-err',
  loginFailed: '.cd-login__login-failed',
  registerLink: '.cd-login__register a',
  forgotPasswordLink: '.cd-login__forgot-password a',
};