---
version: 2
jobs:
  build:
    working_directory: ~/cp-zen-frontend
    docker:
      - image: node:8.4
        environment:
          LANG: en_US.utf8
    steps:
      - checkout
      - run:
          name: Install jq
          command: |
            apt-get update
            apt-get install jq
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            yarn
            BUILD_BRANCH=$CIRCLE_BRANCH GITHUB_USERNAME=$CIRCLE_PR_USERNAME .circleci/get_cd_deps.sh
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: GIT_BRANCH=$CIRCLE_BRANCH yarn build
      - save_cache:
          key: build-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - dist
  test-e2e:
    working_directory: ~/cp-zen-frontend
    docker:
      - image: node:8.4
        environment:
          LANG: en_US.utf8
          NODE_ENV: e2e
          WDIO_MAX_INSTANCES: 6
      - image: selenium/standalone-chrome:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - build-cache-{{ .Branch }}
            - build-cache
      - run:
          name: Tests
          command: yarn e2e-with-mocks
  test-unit:
    working_directory: ~/cp-zen-frontend
    docker:
      - image: node:8.4
        environment:
          LANG: en_US.utf8
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - build-cache-{{ .Branch }}
            - build-cache
      - run:
          name: install chrome
          command: bash .circleci/install_chrome.sh
      - run:
          name: Tests
          command: yarn unit
  test-lint:
    working_directory: ~/cp-zen-frontend
    docker:
      - image: node:8.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - build-cache-{{ .Branch }}
            - build-cache
      - run:
          name: Tests
          command: yarn lint
  publish:
    working_directory: ~/cp-zen-frontend
    docker:
      - image: node:8.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - build-cache-{{ .Branch }}
            - build-cache
      - run:
          name: setup git
          command: |
            set -eo pipefail
            git config --global user.email "webteam@coderdojo.com"
            git config --global user.name "CoderDojo Foundation"
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: publish to git and npm
          command: |
            npm version patch -m "[skip ci] Update to %s"
            git push
            npm publish
  nightly:
    working_directory: ~/cp-zen-frontend
    docker:
      - image: node:8.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - build-cache-{{ .Branch }}
            - build-cache
      - run:
          name: publish
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            npm --no-git-tag-version version `node build/get-version.js`-`git rev-parse --short HEAD`
            npm publish --tag=staging
  deploy:
    working_directory: ~
    docker:
      - image: node:8.4
    steps:
      - run:
          name: Update frontend
          command: BRANCH=CIRCLE_BRANCH ./circleci/update_frontend.sh
  stage:
    working_directory: ~
    docker:
      - image: node:8.4
    steps:
      - run:
          name: Update frontend
          command: BRANCH=CIRCLE_BRANCH ./circleci/update_frontend.sh

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test-unit:
          requires:
            - build
      - test-e2e:
          requires:
            - build
      - test-lint:
          requires:
            - build
      - publish:
          requires:
            - test-unit
            - test-e2e
            - test-lint
          filters:
            branches:
              only:
                - master
      - nightly:
          requires:
            - test-unit
            - test-e2e
            - test-lint
          filters:
            branches:
              only:
                - staging
      - deploy:
          requires:
            - publish
      - stage:
          requires:
            - nightly
