module.exports = {
"topics": [
  {
    "tid": "659",
    "uid": "1075",
    "cid": "1",
    "mainPid": "2455",
    "title": "Astro Pi Community Stories",
    "slug": "659/astro-pi-community-stories",
    "timestamp": "1535032000283",
    "lastposttime": "1535032000283",
    "postcount": "1",
    "viewcount": "28",
    "locked": false,
    "deleted": false,
    "pinned": false,
    "thumb": "",
    "titleRaw": "Astro Pi Community Stories",
    "timestampISO": "2018-08-23T13:46:40.283Z",
    "lastposttimeISO": "2018-08-23T13:46:40.283Z",
    "category": {},
    "user": {},
    "teaser": {},
    "tags": [],
    "isOwner": false,
    "ignored": false,
    "unread": true,
    "bookmark": null,
    "unreplied": false,
    "icons": []
  },
  {
    "tid": "658",
    "uid": "1120",
    "cid": "6",
    "mainPid": "2454",
    "title": "Scratch (etc) programming in Russian",
    "slug": "658/scratch-etc-programming-in-russian",
    "timestamp": "1534784216498",
    "lastposttime": "1534784216498",
    "postcount": "1",
    "viewcount": "32",
    "locked": false,
    "deleted": false,
    "pinned": false,
    "titleRaw": "Scratch (etc) programming in Russian",
    "timestampISO": "2018-08-20T16:56:56.498Z",
    "lastposttimeISO": "2018-08-20T16:56:56.498Z",
    "category": {
      "cid": "6",
      "name": "Learning Resources for Dojos",
      "slug": "6/learning-resources-for-dojos",
      "icon": "fa-pencil-square-o",
      "image": null,
      "bgColor": "#0093D5",
      "color": "#333",
      "disabled": false
      },
    "user": {},
    "teaser": {},
    "tags": [],
    "isOwner": false,
    "ignored": false,
    "unread": true,
    "bookmark": null,
    "unreplied": false,
    "icons": []
  },
  {
    "tid": "656",
    "uid": "1113",
    "cid": "2",
    "mainPid": "2437",
    "title": "What courses are avaialble?",
    "slug": "656/what-courses-are-avaialble",
    "timestamp": "1534362475940",
    "lastposttime": "1534778191354",
    "postcount": "5",
    "viewcount": "101",
    "locked": false,
    "deleted": false,
    "pinned": false,
    "teaserPid": "2453",
    "titleRaw": "What courses are avaialble?",
    "timestampISO": "2018-08-15T19:47:55.940Z",
    "lastposttimeISO": "2018-08-20T15:16:31.354Z",
    "category": {
      "cid": "2",
      "name": "General Discussion",
      "slug": "2/general-discussion",
      "icon": "fa-comments-o",
      "image": null,
      "bgColor": "#0093D5",
      "color": "#fff",
      "disabled": false
      },
    "user": {},
    "teaser": {},
    "tags": [],
    "isOwner": false,
    "ignored": false,
    "unread": true,
    "bookmark": null,
    "unreplied": false,
    "icons": []
  },
  {
    "tid": "657",
    "uid": "1113",
    "cid": "2",
    "mainPid": "2450",
    "title": "Text input box",
    "slug": "657/text-input-box",
    "timestamp": "1534447989271",
    "lastposttime": "1534513684410",
    "postcount": "2",
    "viewcount": "53",
    "locked": false,
    "deleted": false,
    "pinned": false,
    "teaserPid": "2451",
    "titleRaw": "Text input box",
    "timestampISO": "2018-08-16T19:33:09.271Z",
    "lastposttimeISO": "2018-08-17T13:48:04.410Z",
    "category": {
      "cid": "2",
      "name": "General Discussion",
      "slug": "2/general-discussion",
      "icon": "fa-comments-o",
      "image": null,
      "bgColor": "#0093D5",
      "color": "#fff",
      "disabled": false
      },
    "user": {},
    "teaser": {},
    "tags": [],
    "isOwner": false,
    "ignored": false,
    "unread": true,
    "bookmark": null,
    "unreplied": false,
    "icons": []
  },
  {
    "tid": "604",
    "uid": "1060",
    "cid": "2",
    "mainPid": "2276",
    "title": "Anything for parents?",
    "slug": "604/anything-for-parents",
    "timestamp": "1526535836201",
    "lastposttime": "1534447740701",
    "postcount": "13",
    "viewcount": "539",
    "locked": false,
    "deleted": false,
    "pinned": false,
    "teaserPid": "2449",
    "titleRaw": "Anything for parents?",
    "timestampISO": "2018-05-17T05:43:56.201Z",
    "lastposttimeISO": "2018-08-16T19:29:00.701Z",
    "category": {
      "cid": "2",
      "name": "General Discussion",
      "slug": "2/general-discussion",
      "icon": "fa-comments-o",
      "image": null,
      "bgColor": "#0093D5",
      "color": "#fff",
      "disabled": false
      },
    "user": {},
    "teaser": {},
    "tags": [],
    "isOwner": false,
    "ignored": false,
    "unread": true,
    "bookmark": null,
    "unreplied": false,
    "icons": []
  },
  {
    "tid": "645",
    "uid": "1120",
    "cid": "2",
    "mainPid": "2399",
    "title": "Sharing programming experience here on Coder Dojo?",
    "slug": "645/sharing-programming-experience-here-on-coder-dojo",
    "timestamp": "1533485599274",
    "lastposttime": "1534363309569",
    "postcount": "8",
    "viewcount": "168",
    "locked": false,
    "deleted": false,
    "pinned": false,
    "thumb": "",
    "teaserPid": "2440",
    "titleRaw": "Sharing programming experience here on Coder Dojo?",
    "timestampISO": "2018-08-05T16:13:19.274Z",
    "lastposttimeISO": "2018-08-15T20:01:49.569Z",
    "category": {
      "cid": "2",
      "name": "General Discussion",
      "slug": "2/general-discussion",
      "icon": "fa-comments-o",
      "image": null,
      "bgColor": "#0093D5",
      "color": "#fff",
      "disabled": false
      },
    "user": {},
    "teaser": {},
    "tags": [],
    "isOwner": false,
    "ignored": false,
    "unread": true,
    "bookmark": null,
    "unreplied": false,
    "icons": []
  },
  {
    "tid": "169",
    "uid": "406",
    "cid": "2",
    "mainPid": "578",
    "title": "Visual coding languages for Arduino",
    "slug": "169/visual-coding-languages-for-arduino",
    "timestamp": "1472073605749",
    "lastposttime": "1534362670637",
    "postcount": "5",
    "viewcount": "3096",
    "locked": false,
    "deleted": false,
    "pinned": false,
    "teaserPid": "2438",
    "titleRaw": "Visual coding languages for Arduino",
    "timestampISO": "2016-08-24T21:20:05.749Z",
    "lastposttimeISO": "2018-08-15T19:51:10.637Z",
    "category": {
      "cid": "2",
      "name": "General Discussion",
      "slug": "2/general-discussion",
      "icon": "fa-comments-o",
      "image": null,
      "bgColor": "#0093D5",
      "color": "#fff",
      "disabled": false
      },
    "user": {},
    "teaser": {},
    "tags": [],
    "isOwner": false,
    "ignored": false,
    "unread": true,
    "bookmark": null,
    "unreplied": false,
    "icons": []
  },
],
"categories": [
  {
  "cid": "1",
  "name": "Community Announcements",
  "slug": "1/announcements",
  "icon": "fa-bullhorn",
  "link": "",
  "color": "#fff",
  "bgColor": "#49B749",
  "parentCid": "0",
  "selected": false,
  "children": [],
  "level": ""
  },
  {
  "cid": "2",
  "name": "General Discussion",
  "slug": "2/general-discussion",
  "icon": "fa-comments-o",
  "link": "",
  "color": "#fff",
  "bgColor": "#0093D5",
  "parentCid": "0",
  "selected": false,
  "children": [],
  "level": ""
  },
  {
  "cid": "17",
  "name": "Platform Discussion",
  "slug": "17/zen-platform-discussion",
  "icon": "fa-comments",
  "link": "",
  "color": "#fff",
  "bgColor": "#73449B",
  "parentCid": "0",
  "selected": false,
  "children": [],
  "level": ""
  },
  {
  "cid": "10",
  "name": "Equality, Diversity &amp; Accessibility",
  "slug": "10/coderdojo-girls",
  "icon": "fa-female",
  "link": "",
  "color": "#fff",
  "bgColor": "#FAA31A",
  "parentCid": "0",
  "selected": false,
  "children": [],
  "level": ""
  },
  {
  "cid": "29",
  "name": "Organising a Dojo",
  "slug": "29/organising-a-dojo",
  "icon": "fa-folder-open-o",
  "link": "",
  "color": "#333",
  "bgColor": "#49B749",
  "parentCid": "0",
  "selected": false,
  "children": [
  {
  "cid": "4",
  "name": "Support Forum",
  "slug": "4/support-forum",
  "icon": "fa-question",
  "link": "",
  "color": "#333",
  "bgColor": "#FAA31A",
  "parentCid": "29",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  },
  {
  "cid": "5",
  "name": "Organising and Managing your Dojo",
  "slug": "5/organising-and-managing-your-dojo",
  "icon": "fa-gavel",
  "link": "",
  "color": "#333",
  "bgColor": "#49B749",
  "parentCid": "29",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  }
  ],
  "level": ""
  },
  {
  "cid": "4",
  "name": "Support Forum",
  "slug": "4/support-forum",
  "icon": "fa-question",
  "link": "",
  "color": "#333",
  "bgColor": "#FAA31A",
  "parentCid": "29",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  },
  {
  "cid": "5",
  "name": "Organising and Managing your Dojo",
  "slug": "5/organising-and-managing-your-dojo",
  "icon": "fa-gavel",
  "link": "",
  "color": "#333",
  "bgColor": "#49B749",
  "parentCid": "29",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  },
  {
  "cid": "28",
  "name": "Learning Resources and Recommended Practices",
  "slug": "28/leaning-resources-content",
  "icon": "fa-book",
  "link": "",
  "color": "#333",
  "bgColor": "#0093D5",
  "parentCid": "0",
  "selected": false,
  "children": [
  {
  "cid": "6",
  "name": "Learning Resources for Dojos",
  "slug": "6/learning-resources-for-dojos",
  "icon": "fa-pencil-square-o",
  "link": "",
  "color": "#333",
  "bgColor": "#0093D5",
  "parentCid": "28",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  },
  {
  "cid": "8",
  "name": "Learning Philosophies and Practices!",
  "slug": "8/learning-philosophies-and-practices",
  "icon": "fa-graduation-cap",
  "link": "",
  "color": "#fff",
  "bgColor": "#73449B",
  "parentCid": "28",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  },
  {
  "cid": "9",
  "name": "Child Protection Best Practices",
  "slug": "9/child-protection-best-practices",
  "icon": "fa-users",
  "link": "",
  "color": "#fff",
  "bgColor": "#FAA31A",
  "parentCid": "28",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  }
  ],
  "level": ""
  },
  {
  "cid": "6",
  "name": "Learning Resources for Dojos",
  "slug": "6/learning-resources-for-dojos",
  "icon": "fa-pencil-square-o",
  "link": "",
  "color": "#333",
  "bgColor": "#0093D5",
  "parentCid": "28",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  },
  {
  "cid": "8",
  "name": "Learning Philosophies and Practices!",
  "slug": "8/learning-philosophies-and-practices",
  "icon": "fa-graduation-cap",
  "link": "",
  "color": "#fff",
  "bgColor": "#73449B",
  "parentCid": "28",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  },
  {
  "cid": "9",
  "name": "Child Protection Best Practices",
  "slug": "9/child-protection-best-practices",
  "icon": "fa-users",
  "link": "",
  "color": "#fff",
  "bgColor": "#FAA31A",
  "parentCid": "28",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  },
  {
  "cid": "27",
  "name": "CoderDojo Regional Bodies",
  "slug": "27/coderdojo-regional-bodies",
  "icon": "fa-comments",
  "link": "",
  "color": "#049b75",
  "bgColor": "#86C1B9",
  "parentCid": "0",
  "selected": false,
  "children": [
  {
  "cid": "15",
  "name": "CoderDojo WA",
  "slug": "15/coderdojo-wa",
  "icon": "hidden",
  "link": "",
  "color": "#333",
  "bgColor": "#ff9d2e",
  "parentCid": "27",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  },
  {
  "cid": "18",
  "name": "CoderDojo Ireland",
  "slug": "18/coderdojo-ireland",
  "icon": "fa-wpbeginner",
  "link": "",
  "color": "#333",
  "bgColor": "#86C1B9",
  "parentCid": "27",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  },
  {
  "cid": "24",
  "name": "CoderDojo Spain",
  "slug": "24/coderdojo-spain",
  "icon": "fa-comments",
  "link": "",
  "color": "#333",
  "bgColor": "#86C1B9",
  "parentCid": "27",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  },
  {
  "cid": "21",
  "name": "CoderDojo Netherlands",
  "slug": "21/coderdojo-netherlands",
  "icon": "hidden",
  "link": "",
  "color": "#333",
  "bgColor": "#fc1717",
  "parentCid": "27",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  },
  {
  "cid": "25",
  "name": "CoderDojo Japan",
  "slug": "25/coderdojo-japan",
  "icon": "hidden",
  "link": "",
  "color": "#333",
  "bgColor": "#F7CA88",
  "parentCid": "27",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  }
  ],
  "level": ""
  },
  {
  "cid": "15",
  "name": "CoderDojo WA",
  "slug": "15/coderdojo-wa",
  "icon": "hidden",
  "link": "",
  "color": "#333",
  "bgColor": "#ff9d2e",
  "parentCid": "27",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  },
  {
  "cid": "18",
  "name": "CoderDojo Ireland",
  "slug": "18/coderdojo-ireland",
  "icon": "fa-wpbeginner",
  "link": "",
  "color": "#333",
  "bgColor": "#86C1B9",
  "parentCid": "27",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  },
  {
  "cid": "24",
  "name": "CoderDojo Spain",
  "slug": "24/coderdojo-spain",
  "icon": "fa-comments",
  "link": "",
  "color": "#333",
  "bgColor": "#86C1B9",
  "parentCid": "27",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  },
  {
  "cid": "21",
  "name": "CoderDojo Netherlands",
  "slug": "21/coderdojo-netherlands",
  "icon": "hidden",
  "link": "",
  "color": "#333",
  "bgColor": "#fc1717",
  "parentCid": "27",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  },
  {
  "cid": "25",
  "name": "CoderDojo Japan",
  "slug": "25/coderdojo-japan",
  "icon": "hidden",
  "link": "",
  "color": "#333",
  "bgColor": "#F7CA88",
  "parentCid": "27",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  },
  {
  "cid": "32",
  "name": "Other Dojo Groups",
  "slug": "32/other-dojo-groups",
  "icon": "fa-comments",
  "link": "",
  "color": "#fff",
  "bgColor": "#A1B56C",
  "parentCid": "0",
  "selected": false,
  "children": [
  {
  "cid": "16",
  "name": "Tramore Dojo",
  "slug": "16/tramore-dojo",
  "icon": "fa-comments",
  "link": "",
  "color": "#fff",
  "bgColor": "#DC9656",
  "parentCid": "32",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  },
  {
  "cid": "23",
  "name": "CoderDojo Turkey",
  "slug": "23/coderdojo-turkey",
  "icon": "fa-comments",
  "link": "",
  "color": "#fff",
  "bgColor": "#DC9656",
  "parentCid": "32",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  },
  {
  "cid": "26",
  "name": "MegaDojo",
  "slug": "26/megadojo",
  "icon": "fa-comments",
  "link": "",
  "color": "#fff",
  "bgColor": "#7CAFC2",
  "parentCid": "32",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  }
  ],
  "level": ""
  },
  {
  "cid": "16",
  "name": "Tramore Dojo",
  "slug": "16/tramore-dojo",
  "icon": "fa-comments",
  "link": "",
  "color": "#fff",
  "bgColor": "#DC9656",
  "parentCid": "32",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  },
  {
  "cid": "23",
  "name": "CoderDojo Turkey",
  "slug": "23/coderdojo-turkey",
  "icon": "fa-comments",
  "link": "",
  "color": "#fff",
  "bgColor": "#DC9656",
  "parentCid": "32",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  },
  {
  "cid": "26",
  "name": "MegaDojo",
  "slug": "26/megadojo",
  "icon": "fa-comments",
  "link": "",
  "color": "#fff",
  "bgColor": "#7CAFC2",
  "parentCid": "32",
  "selected": false,
  "children": [],
  "level": "&nbsp;&nbsp;&nbsp;&nbsp;"
  }
],
"loggedIn": false,
"url": "/recent/new",
"bodyClass": "page-recent page-recent-new"
}